<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>$(TargetFrameworksForLibraries)</TargetFrameworks>
    <TargetFrameworks Condition="$(OS) == 'Windows_NT'">$(TargetFrameworks);$(NetFrameworkMinimumSupportedVersion)</TargetFrameworks>
    <Description>OpenTelemetry Resource Detector for the build artifact of the running application.</Description>
    <PackageTags>$(PackageTags);artifact;purl</PackageTags>
    <MinVerTagPrefix>Resources.Artifact-</MinVerTagPrefix>
  </PropertyGroup>

  <PropertyGroup Condition="'$([MSBuild]::GetTargetFrameworkIdentifier(`$(TargetFramework)`))' == '.NETCoreApp'">
    <IsAotCompatible>true</IsAotCompatible>
  </PropertyGroup>

  <!-- Do not run Package Baseline Validation as this package has never released a stable version.
  Remove this property once we have released a stable version and add PackageValidationBaselineVersion property. -->
  <PropertyGroup>
    <DisablePackageBaselineValidation>true</DisablePackageBaselineValidation>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="OpenTelemetry" />
    <PackageReference Include="System.Text.Json" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="$(RepoRoot)\src\Shared\AssemblyVersionExtensions.cs" Link="Includes\AssemblyVersionExtensions.cs" />
    <Compile Include="$(RepoRoot)\src\Shared\DepsManifest.cs" Link="Includes\DepsManifest.cs" />
    <Compile Include="$(RepoRoot)\src\Shared\DepsManifestPackage.cs" Link="Includes\DepsManifestPackage.cs" Condition="'$([MSBuild]::GetTargetFrameworkIdentifier(`$(TargetFramework)`))' == '.NETCoreApp'" />
    <Compile Include="$(RepoRoot)\src\Shared\Guard.cs" Link="Includes\Guard.cs" />
    <Compile Include="$(RepoRoot)\src\Shared\SchemaUrls.cs" Link="Includes\SchemaUrls.cs" />
  </ItemGroup>

</Project>
