<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>$(TargetFrameworksForLibraries)</TargetFrameworks>
    <TargetFrameworks Condition="$(OS) == 'Windows_NT'">$(TargetFrameworks);$(NetFrameworkMinimumSupportedVersion)</TargetFrameworks>
    <Description>Reports the NuGet packages deployed with an application, for correlation against known vulnerabilities.</Description>
    <PackageTags>$(PackageTags);dependencies;sbom;purl</PackageTags>
    <MinVerTagPrefix>Instrumentation.DependencyInventory-</MinVerTagPrefix>
  </PropertyGroup>

  <PropertyGroup Condition="'$([MSBuild]::GetTargetFrameworkIdentifier(`$(TargetFramework)`))' == '.NETCoreApp'">
    <IsAotCompatible>true</IsAotCompatible>
  </PropertyGroup>

  <!-- Do not run Package Baseline Validation as this package has never released a stable version.
  Remove this property once we have released a stable version and add PackageValidationBaselineVersion property. -->
  <PropertyGroup>
    <DisablePackageBaselineValidation>true</DisablePackageBaselineValidation>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration" />
    <PackageReference Include="OpenTelemetry" />
    <PackageReference Include="System.Text.Json" Condition="'$([MSBuild]::GetTargetFrameworkIdentifier(`$(TargetFramework)`))' != '.NETCoreApp'" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="$(RepoRoot)\src\Shared\Configuration\*.cs" Link="Includes\Configuration\%(Filename).cs" />
    <Compile Include="$(RepoRoot)\src\Shared\DepsManifest.cs" Link="Includes\DepsManifest.cs" />
    <Compile Include="$(RepoRoot)\src\Shared\DepsManifestPackage.cs" Link="Includes\DepsManifestPackage.cs" Condition="'$([MSBuild]::GetTargetFrameworkIdentifier(`$(TargetFramework)`))' == '.NETCoreApp'" />
    <Compile Include="$(RepoRoot)\src\Shared\Guard.cs" Link="Includes\Guard.cs" />
  </ItemGroup>

</Project>
